# Generated by Django 3.2.3 on 2021-07-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210724_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pay_interval',
            field=models.CharField(choices=[('month', 'month'), ('quarter', 'quarter'), ('half', 'half'), ('yearly', 'yearly')], help_text='원', max_length=100),
        ),
    ]
