# Generated by Django 3.2.3 on 2021-07-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_service_pay_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.CharField(help_text='원', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='pay_interval',
            field=models.CharField(choices=[('month', 'month'), ('quarter', 'quarter'), ('half', 'half'), ('yearly', 'yearly')], max_length=100),
        ),
    ]
